[tox]
envlist = lint, py27

[testenv]
deps = -r test-requirements.txt
commands =
    pytest --cov fulgurate test --cov-report term --cov-report xml:coverage.xml test/

[testenv:lint]
deps = -r test-requirements.txt
commands =
    pylint src/fulgurate/
    pylint --rcfile test/pylintrc test/
