name: Python

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: LizardByte/actions/actions/setup_python@master
      with:
        python-version: '2.7'
    - name: Install tox
      run: pip install tox
    - name: Run tox
      run: tox
